# Generated by Django 4.2.6 on 2023-11-02 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_address_employee_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='course',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
